#!/usr/bin/env bash

set -e -u -o pipefail

suffix="$1"

indir='tex'
outdir='data'
tmpdir='tmp'

infile='cv'"$suffix"

cd "$indir"
pdflatex --output-directory="$OLDPWD"'/'"$tmpdir" "$infile"
pdflatex --output-directory="$OLDPWD"'/'"$tmpdir" "$infile"
cd "-"
mv "$tmpdir"'/'"$infile"'.pdf' "$outdir"
